apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: healthylife-metrics
  namespace: monitoring
  labels:
    app: healthylife
spec:
  selector:
    matchLabels:
      app: healthylife-backend
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'jvm_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'process_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'http_.*'
      action: keep
    - sourceLabels: [__name__]
      regex: 'healthylife_.*'
      action: keep
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: healthylife-pods
  namespace: monitoring
  labels:
    app: healthylife
spec:
  selector:
    matchLabels:
      app: healthylife-backend
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: healthylife-recording-rules
  namespace: monitoring
  labels:
    app: healthylife
spec:
  groups:
  - name: healthylife.recording.rules
    interval: 1m
    rules:
    - record: healthylife:request_duration_seconds:avg5m
      expr: rate(http_server_requests_seconds_sum[5m]) / rate(http_server_requests_seconds_count[5m])
    
    - record: healthylife:error_rate:5m
      expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100
    
    - record: healthylife:active_users:daily
      expr: count(count by (user_id) (healthylife_user_activity_total{period="daily"}))
    
    - record: healthylife:metrics_added:daily
      expr: sum(increase(healthylife_metrics_added_total[24h]))
    
    - record: healthylife:reports_generated:daily
      expr: sum(increase(healthylife_reports_generated_total[24h]))
    
    - record: healthylife:cache_hit_ratio:5m
      expr: rate(healthylife_cache_hits_total[5m]) / (rate(healthylife_cache_hits_total[5m]) + rate(healthylife_cache_misses_total[5m])) * 100
    
    - record: healthylife:db_connection_usage:5m
      expr: avg_over_time(healthylife_db_connections_active[5m]) / avg_over_time(healthylife_db_connections_max[5m]) * 100
    
    - record: healthylife:api_success_rate:5m
      expr: sum(rate(http_server_requests_seconds_count{status=~"2.."}[5m])) / sum(rate(http_server_requests_seconds_count[5m])) * 100 