apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthylife-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthylife-backend
  template:
    metadata:
      labels:
        app: healthylife-backend
    spec:
      containers:
      - name: healthylife-backend
        image: healthylife:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: healthylife-config
              key: spring.profiles.active
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password 