spring:
  application:
    name: healthylife
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/healthylife
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key}
    expiration: 86400000

logging:
  level:
    root: INFO
    com.healthylife: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: Authorization
  allow-credentials: true
  max-age: 3600 